export const TRAINS_FOUND = 'TRAINS_FOUND';
export const SET_DATE = 'SET_DATE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOADING = 'USER_LOADING';
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_TICKET = 'CREATE_TICKET';
export const SET_FLASH_MESSAGE = "SET_FLASH_MESSAGE";
export const RESET_FLASH_MESSAGE = "RESET_FLASH_MESSAGE";